icon select
UofA-Blueprint/AlzheimerCalgary2.0 pull request #14
Opened 2024-03-13 21:03 UTC by woopy098

Icon select implemented

2024-03-13 22:00 UTC, TienDucHo requested changes
Please read my review! Thanks!

2024-03-13 22:00 UTC, TienDucHo commented on src/components/IconOption.tsx
> +        <div className={`inline-flex justify-center items-center border-4 ${selected ? 'border-blue-500' : 'border-transparent'}`}>
Border should be rounded when selected

2024-03-23 21:44 UTC, woopy098 commented on src/components/IconOption.tsx
> +    color: string;
color prop change to be className

2024-03-23 21:44 UTC, woopy098 commented on src/components/IconOption.tsx
> +        <div className={`inline-flex justify-center items-center border-4 ${selected ? 'border-blue-500' : 'border-transparent'}`}>
border is rounded

2024-04-01 22:05 UTC, TienDucHo approved these changes

2024-04-01 22:06 UTC, merged