ASC-73
UofA-Blueprint/AlzheimerCalgary2.0 pull request #8
Opened 2024-02-19 21:55 UTC by khanheric2003

Implemented component, needs feedback on sizing the fonts, padding, and margin between elements inside the drop box

2024-02-23 20:31 UTC, TienDucHo requested changes
Please read my comments? Thanks

2024-02-23 20:31 UTC, TienDucHo commented on src/components/MediaUploadZone.tsx
> +  useEffect(() => {
We do not need this, as this can be accomplished by using CSS only (you can use "w-full h-full" to achieve the same thing).

2024-02-23 20:31 UTC, TienDucHo commented on src/components/MediaUploadZone.tsx
> +  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
Good job on implementing the functionality, but this out of the scope for this ticket. Make sure to clarify this for further tickets.

2024-02-26 19:05 UTC, khanheric2003 reviewed
yes

2024-02-26 19:10 UTC, TienDucHo requested changes

2024-02-26 19:10 UTC, TienDucHo commented on src/components/MediaUploadZone.tsx
> +  fontSize = "1em",
I do not think we need to pass font size explicitly like this, can you remove it and tell me what it break?

2024-02-26 19:59 UTC, TienDucHo approved these changes

2024-02-26 20:01 UTC, merged